### ISSUE TITLE
Wrong metatags

### ISSUE THREAD

**Issue by sergeychernyshev** [GoogleChrome/essential-image-optimization#91]
Looks like https://images.guide/ has some wrong metadata tags, shows up as "summary_large_image" on Quora and I can imagine other sites too.

**Comment by lajazianwilliams** [comment]
Okay, I have had this laptop for at least 4 years I think and this is my first time delving this deep within it. I just began taking a coding class approximately three weeks ago. This is new, I'm fearful, and need patience and understanding. I seem to have some issues here, however, so I don't create a big boo boo, I am going extremely slow about doing anything. (lol) I fear making changes, but it is nice knowing what all of this stuff mean, makes it tick, and much more. I am on a learning expedition here people.
